name: Build extension

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install VSCE build tool
        run: npm i @vscode/vsce
      - name: Get version
        run: echo "SYNC_PKG_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
      - run: npm run package
      - uses: actions/upload-artifact@v4
        with:
          name: sync-settings-${{ env.SYNC_PKG_VERSION }}.vsix
          path: sync-settings-${{ env.SYNC_PKG_VERSION }}.vsix
